#!/bin/bash

wait_for_host() {
  if [[ $# -ne 1 ]]; then
    echo "Please provide 1 parameter, the hostname."
    return 1
  fi

  echo -n "Waiting for Host: "
  echo $1

  while ! ping -c 1 $1 &>/dev/null; do :; done
  echo "Host Online"
}
