#!/bin/bash

cdu() {

  if [ -z "$1" ]
  then
    echo "No argument supplied to cdu!"
    return 1
  fi

  NUM_DIRS=$1
  NEW_DIR=$PWD
  for ((i=1; i<=NUM_DIRS;i++))
  do
    NEW_DIR=$NEW_DIR/..
  done

  cd $NEW_DIR  
}
