#!/bin/bash

set -e

echo "Upgrading existing packages..."
sudo apt update
sudo apt upgrade -y

echo "Installing NodeJS and NPM..."
curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
rm -f nodesource_setup.sh
sudo apt install -y nodejs
sudo apt install -y build-essential

echo "Installing Python"
sudo apt install -y python

echo "Installing Watchman Dependencies"
sudo apt install -y libssl-dev autoconf automake libtool python-dev pkg-config

echo "Installing Watchman"
git clone https://github.com/facebook/watchman.git
cd watchman
git checkout v4.9.0  # the latest stable release
./autogen.sh
./configure
make
sudo make install

echo "Installing Nuclide Server"
sudo npm install -g nuclide

echo "Installing Yarn"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install -y yarn

echo "Installing Flow Globally"
sudo npm install -g flow-bin

echo "Finished installing components!"
echo "Make sure your server has a SSH Daemon running and has ports 9090-9093 exposed!"
