#!/bin/bash

set -e

echo "Upgrading existing packages..."
sudo apt update
sudo apt upgrade -y

echo "Installing Python 3..."
sudo apt install -y python3

echo "Installing Pip..."
sudo apt install -y python3-pip

echo "Installing venv..."
sudo apt install -y python3-venv

echo "Installing packages and development tools..."
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev

echo "Finished successfully!"
