#!/bin/bash

set -e

echo "Upgrading existing packages..."
sudo apt update
sudo apt upgrade -y

echo "Installing NodeJS and NPM..."
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
rm -f nodesource_setup.sh
sudo apt install -y nodejs
sudo apt install -y build-essential

echo "Installing Python"
sudo apt install -y python

echo "Installing Watchman Dependencies"
sudo apt install -y libssl-dev autoconf automake libtool python-dev

echo "Installing Watchman"
git clone https://github.com/facebook/watchman.git
cd watchman
git checkout v4.9.0  # the latest stable release
./autogen.sh
./configure
make
sudo make install

echo "Installing Nuclide Server"
sudo npm install -g nuclide


echo "Finished installing components!"
echo "Make sure your server has a SSH Daemon running and has ports 9090-9093 exposed!"
