#!/bin/bash

set -e

if [[ $# -ne 1 ]]; then
  echo "Please provide 1 parameter, the hostname."
  exit 1
fi

echo -n "Waiting for Host: "
echo $1

while ! ping -c 1 $1 &>/dev/null; do :; done
echo "Host Online"
